# Generated by Django 3.2.6 on 2021-10-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Add new author'), ('can_update_author', 'Update new author'), ('can_delete_author', 'Delete new author'))},
        ),
    ]
